# Generated by Django 4.1.9 on 2023-05-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(default='Bad Habits', max_length=30)),
                ('artist', models.CharField(default='Ed Sheeran', max_length=20)),
                ('acousticness', models.FloatField(default=0)),
                ('danceability', models.FloatField(default=0)),
                ('liveness', models.FloatField(default=0)),
                ('Favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
